name: geopoint_repository

version: 1.0.0+2

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.6
  equatable: ^2.0.0
  firebase_core: ^1.0.0
  hive: ^2.0.4
  rxdart: ^0.27.3
