name: authentication_repository
description: Dart package which manages authentication domain.
version: 1.0.0+2

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0 
  firebase_auth: ^3.3.5
  firebase_core: ^1.0.0
  google_sign_in: ^5.0.0
  meta: ^1.3.0
  

dev_dependencies:
