name: location_picker_with_google_maps

version: 1.0.0+2

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.2
  equatable: ^2.0.0
  flutter_bloc: ^8.0.1
  geocoding: ^2.0.0
  hive: ^2.0.4
  geolocator: ^8.0.3
  google_maps_flutter: ^2.0.4
